### ISSUE TITLE
Warning: compatibility issue between library and framework

### ISSUE THREAD

**Issue by IU5HKU** [iw5ejm/multibandWSPR_nodeMCU#1]
If you are using ESP8266 framework v2.4.2 you will encounter a linker error, because this framework and JTEncode library (all versions) both uses 'crc_update' as function name, resulting in a conflict. 
To resolve simply upgrade the framework, 2.5.0beta2 at moment is working ok, (but is a beta), you can downgrade to 2.4.1 if you prefer and this will resolve too.
Thanks for this interesting piece of code
 MC

**Comment by iw5ejm** [comment]
Thanks Marco, noted in header the libraries versions needed to compile successfully the code!
