### ISSUE TITLE
Wrong voltage for SI5351

### ISSUE THREAD

**Issue by palbeda** [iw5ejm/multibandWSPR_nodeMCU#2]
Thanks for this interesting project. I always like simple designs. 

When I built it, I noted the frequency was a lot higher than expected. Then I noted that the SI5351 is supposed to work on 3.3 Volt and the jpeg file clearly shows it is connected to +5 Volt and I copied that blindly. When I connected the Vin terminal of the SI5351 to the 3.3V terminal on the ESP instead, the freqency became as expected.
I read that 5 V will eventually damage the SI5351

Best regards and keep making these briljantly simple designs, Peter

**Comment by iw5ejm** [comment]
Thanks man for the correction! 
Wrong image removed!

Best regards!
Marco
